In [3]:
from __future__ import print_function
import torch as t

In [2]:
#指定tensor的形状
a=t.Tensor(2,3)
a

tensor([[5.8518e+21, 4.5710e-41, 7.7819e+24],
        [3.0653e-41, 4.4842e-44, 0.0000e+00]])

In [3]:
#用list的数据创建tensor
b=t.Tensor([[1,2,3],[4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [5]:
b_size=b.size()
b.size

<function Tensor.size>

In [6]:
b_size

torch.Size([2, 3])

In [7]:
b.numel()#b中元素总个数

6

In [8]:
#创建一个和b形状一样的tensor
c=t.Tensor(b_size)
d=t.Tensor((2,3))
c,d

(tensor([[7.6823e+24, 3.0653e-41, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 0.0000e+00]]), tensor([2., 3.]))

In [9]:
c.shape

torch.Size([2, 3])

In [10]:
t.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
t.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
t.arange(1,6,2)

tensor([1, 3, 5])

In [13]:
t.linspace(1,10,3)

tensor([ 1.0000,  5.5000, 10.0000])

In [14]:
t.randn(2,3)

tensor([[ 0.2076, -0.1798, -0.7513],
        [ 0.6362,  0.7903, -0.5652]])

In [15]:
t.randperm(5)

tensor([3, 1, 4, 0, 2])

In [16]:
t.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [17]:
t.eye(10,10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
a=t.arange(0,6)
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [20]:
b=a.view(-1,3)#当某一维是-1时，会自动计算它的大小

In [21]:
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [22]:
b.unsqueeze(1)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [23]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [24]:
c=b.view(1,1,1,2,3)
c.squeeze(0)

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [25]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [26]:
a[1]=100
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [28]:
b.resize_(1,3)
b

tensor([[  0, 100,   2]])

In [29]:
b.resize_(3,3)
b

tensor([[                  0,                 100,                   2],
        [                  3,                   4,                   5],
        [       176093659187, 3919320493604431412,                  80]])

In [30]:
a=t.randn(3,4)
a

tensor([[-1.4671,  0.1279,  0.8196,  0.9537],
        [ 0.8996,  0.3174,  0.1471,  1.2525],
        [-0.4807, -0.0608, -0.5965, -1.3235]])

In [31]:
a[0]

tensor([-1.4671,  0.1279,  0.8196,  0.9537])

In [32]:
a[:,0]

tensor([-1.4671,  0.8996, -0.4807])

In [33]:
a[0][2]

tensor(0.8196)

In [34]:
a[0,-1]

tensor(0.9537)

In [35]:
a[:2]

tensor([[-1.4671,  0.1279,  0.8196,  0.9537],
        [ 0.8996,  0.3174,  0.1471,  1.2525]])

In [36]:
a[:2,0:2]

tensor([[-1.4671,  0.1279],
        [ 0.8996,  0.3174]])

In [37]:
print(a[0:1, :2])
print(a[0, :2])

tensor([[-1.4671,  0.1279]])
tensor([-1.4671,  0.1279])


In [38]:
a > 1

tensor([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [39]:
a[a>1]#等价于a.masker_select(a>1)
#选择结果与原tensor不共享内存空间

tensor([1.2525])

In [40]:
a[t.LongTensor([0, 1])]

tensor([[-1.4671,  0.1279,  0.8196,  0.9537],
        [ 0.8996,  0.3174,  0.1471,  1.2525]])

# Tensor类型

In [46]:
#设置默认tensor,注意参数是字符串
t.set_default_tensor_type('torch.FloatTensor')

In [47]:
a=t.Tensor(2,3)
a

tensor([[7.6918e+24, 3.0653e-41, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])

In [48]:
b=a.Int()

AttributeError: 'Tensor' object has no attribute 'Int'

In [49]:
b=a,int()

In [50]:
b

(tensor([[7.6918e+24, 3.0653e-41, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 0.0000e+00]]), 0)

In [51]:
b=a.int()
b

tensor([[-2147483648,           0,           0],
        [          0,           0,           0]], dtype=torch.int32)

In [52]:
c=a.type_as(b)
c

tensor([[-2147483648,           0,           0],
        [          0,           0,           0]], dtype=torch.int32)

In [53]:
d=a.new(2,3)
d

tensor([[8.0264e+24, 3.0653e-41, 1.4013e-45],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [55]:
a.new??

In [3]:
t.rand(8,1)

tensor([[0.0372],
        [0.0219],
        [0.9931],
        [0.6611],
        [0.6839],
        [0.5134],
        [0.5544],
        [0.1252]])

In [4]:
t.randn(8,1)

tensor([[-0.0301],
        [-0.2048],
        [ 1.4425],
        [-1.2116],
        [-0.7014],
        [ 0.9423],
        [ 0.2866],
        [ 0.6341]])

In [6]:
w=t.rand(1,1)
w

tensor([[0.8138]])

In [11]:
b=t.zeros(1,1)
b

tensor([[0.]])

In [12]:
y=t.rand(4,1)
y

tensor([[0.7363],
        [0.1825],
        [0.8312],
        [0.3280]])

In [13]:
b=b.expand_as(y)
b

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [14]:
y=y.mean()
y

tensor(0.5195)

In [15]:
b

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [17]:
x=t.rand(4,1)
x

tensor([[0.4123],
        [0.5684],
        [0.2537],
        [0.9820]])

In [31]:
y=t.rand(4,1)
y

tensor([[0.9033],
        [0.1960],
        [0.3332],
        [0.1337]])

In [32]:
y=x.t().mm(y)
y

tensor([[0.6997]])

In [36]:
a = t.arange(0, 6).view(-1, 1)
a

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [5]:
temp=t.randn(3)
temp

tensor([ 0.6301, -0.0053,  1.1465])

In [6]:
temp2=t.randn(4,3)
temp2

tensor([[-0.5731,  0.1659,  0.6006],
        [-0.0272, -2.4239, -0.1117],
        [ 0.2595, -0.1275, -0.1503],
        [-0.6330,  1.2817,  0.1388]])

In [8]:
temp3=temp.expand_as(temp2)
temp3

tensor([[ 0.6301, -0.0053,  1.1465],
        [ 0.6301, -0.0053,  1.1465],
        [ 0.6301, -0.0053,  1.1465],
        [ 0.6301, -0.0053,  1.1465]])

In [10]:
temp4=t.zeros(4)
temp4

tensor([0., 0., 0., 0.])

In [12]:
temp5=t.rand(1,3,4,4)
temp5

tensor([[[[0.7074, 0.5824, 0.3831, 0.9311],
          [0.7356, 0.7829, 0.7968, 0.5452],
          [0.5667, 0.8501, 0.2855, 0.7899],
          [0.9652, 0.0809, 0.1967, 0.8653]],

         [[0.0387, 0.1591, 0.1438, 0.8747],
          [0.3150, 0.4610, 0.4435, 0.0591],
          [0.3999, 0.4702, 0.8434, 0.1860],
          [0.2778, 0.9649, 0.4584, 0.4269]],

         [[0.9757, 0.3166, 0.4818, 0.1510],
          [0.4684, 0.9789, 0.6845, 0.9137],
          [0.1170, 0.6059, 0.4351, 0.2638],
          [0.3468, 0.1447, 0.2849, 0.1464]]]])

In [13]:
temp6=t.randn(2,3,4)
temp6

tensor([[[-0.8136,  2.3362, -0.6212,  0.2364],
         [-1.5546,  0.5089, -0.0591,  0.3249],
         [-1.2444, -0.5112, -1.3773,  1.3821]],

        [[-0.3734,  1.6315,  3.2140, -0.6753],
         [-1.4820, -1.4377,  1.7126,  0.3846],
         [ 0.1286,  0.8934, -1.8149, -1.9991]]])